### ISSUE TITLE
navicat 工具连接查询报错？

### ISSUE THREAD

**Issue by aiaix** [MyCATApache/Mycat-doc#52]
mycat 1.5.1

11/16 15:49:34.982  ERROR [$_NIOREACTOR-2-RW] (DruidMycatRouteStrategy.java:53) -DruidMycatRouteStrategyError
com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual ERROR DURATION
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:1471)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:693)
	at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:658)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:480)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:555)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:166)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:119)
	at com.alibaba.druid.sql.parser.SQLExprParser.exprList(SQLExprParser.java:789)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:690)
	at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:658)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:480)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectItem(SQLSelectParser.java:298)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:275)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:127)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:60)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:196)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:145)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:1658)
	at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:50)
	at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:76)
	at org.opencloudb.route.RouteService.route(RouteService.java:133)
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:224)
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:175)
	at org.opencloudb.server.handler.SelectHandler.handle(SelectHandler.java:106)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:77)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:100)
	at java.lang.Thread.run(Thread.java:744)
11/16 15:49:34.984   WARN [$_NIOREACTOR-2-RW] (ServerConnection.java:232) -ServerConnection [id=14, schema=TESTDB, host=10.20.37.67, user=test,txIsolation=3, autocommit=true, schema=TESTDB]SELECT STATE AS `状态`, ROUND(SUM(DURATION),7) AS `期间`, CONCAT(ROUND(SUM(DURATION)/*100,3), '%') AS `百分比` FROM INFORMATION_SCHEMA.PROFILING WHERE QUERY_ID= GROUP BY STATE ORDER BY SEQ err:java.sql.SQLSyntaxErrorException: com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual ERROR DURATION
java.sql.SQLSyntaxErrorException: com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual ERROR DURATION
	at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:54)
	at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:76)
	at org.opencloudb.route.RouteService.route(RouteService.java:133)
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:224)
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:175)
	at org.opencloudb.server.handler.SelectHandler.handle(SelectHandler.java:106)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:77)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:100)
	at java.lang.Thread.run(Thread.java:744)
Caused by: com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual ERROR DURATION
	at com.alibaba.druid.sql.parser.SQLExprParser.accept(SQLExprParser.java:1471)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:693)
	at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:658)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:480)
	at com.alibaba.druid.sql.parser.SQLExprParser.primary(SQLExprParser.java:555)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primary(MySqlExprParser.java:166)
	at com.alibaba.druid.sql.parser.SQLExprParser.expr(SQLExprParser.java:119)
	at com.alibaba.druid.sql.parser.SQLExprParser.exprList(SQLExprParser.java:789)
	at com.alibaba.druid.sql.parser.SQLExprParser.methodRest(SQLExprParser.java:690)
	at com.alibaba.druid.sql.parser.SQLExprParser.primaryRest(SQLExprParser.java:658)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlExprParser.primaryRest(MySqlExprParser.java:480)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectItem(SQLSelectParser.java:298)
	at com.alibaba.druid.sql.parser.SQLSelectParser.parseSelectList(SQLSelectParser.java:275)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlSelectParser.query(MySqlSelectParser.java:127)
	at com.alibaba.druid.sql.parser.SQLSelectParser.select(SQLSelectParser.java:60)
	at com.alibaba.druid.sql.dialect.mysql.parser.MySqlStatementParser.parseSelect(MySqlStatementParser.java:196)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatementList(SQLStatementParser.java:145)
	at com.alibaba.druid.sql.parser.SQLStatementParser.parseStatement(SQLStatementParser.java:1658)
	at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:50)
	... 15 more
11/16 15:49:35.067   WARN [$_NIOREACTOR-2-RW] (DruidSelectParser.java:393) - find no Route:SELECT * FROM `testdb1`.`goods` LIMIT 0
11/16 15:49:35.067   WARN [$_NIOREACTOR-2-RW] (ServerConnection.java:232) -ServerConnection [id=14, schema=TESTDB, host=10.20.37.67, user=test,txIsolation=3, autocommit=true, schema=TESTDB]SELECT * FROM `testdb1`.`goods` LIMIT 0 err:java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `testdb1`.`goods` LIMIT 0
java.sql.SQLNonTransientException:  find no Route:SELECT * FROM `testdb1`.`goods` LIMIT 0
	at org.opencloudb.parser.druid.impl.DruidSelectParser.tryRoute(DruidSelectParser.java:394)
	at org.opencloudb.parser.druid.impl.DruidSelectParser.changeSql(DruidSelectParser.java:257)
	at org.opencloudb.parser.druid.impl.DefaultDruidParser.parser(DefaultDruidParser.java:66)
	at org.opencloudb.route.impl.DruidMycatRouteStrategy.routeNormalSqlWithAST(DruidMycatRouteStrategy.java:64)
	at org.opencloudb.route.impl.AbstractRouteStrategy.route(AbstractRouteStrategy.java:76)
	at org.opencloudb.route.RouteService.route(RouteService.java:133)
	at org.opencloudb.server.ServerConnection.routeEndExecuteSQL(ServerConnection.java:224)
	at org.opencloudb.server.ServerConnection.execute(ServerConnection.java:175)
	at org.opencloudb.server.handler.SelectHandler.handle(SelectHandler.java:106)
	at org.opencloudb.server.ServerQueryHandler.query(ServerQueryHandler.java:77)
	at org.opencloudb.net.FrontendConnection.query(FrontendConnection.java:308)
	at org.opencloudb.net.handler.FrontendCommandHandler.handle(FrontendCommandHandler.java:71)
	at org.opencloudb.net.FrontendConnection.rawHandle(FrontendConnection.java:435)
	at org.opencloudb.net.FrontendConnection.handle(FrontendConnection.java:417)
	at org.opencloudb.net.AbstractConnection.onReadData(AbstractConnection.java:313)
	at org.opencloudb.net.NIOSocketWR.asynRead(NIOSocketWR.java:186)
	at org.opencloudb.net.AbstractConnection.asynRead(AbstractConnection.java:274)
	at org.opencloudb.net.NIOReactor$RW.run(NIOReactor.java:100)
	at java.lang.Thread.run(Thread.java:744)

**Comment by aiaix** [comment]
navicat连接mycat查询正常，但是后台日志却报这样的错误，是什么情况？
